export const SET_CURRENT_CARECOMPANY = 'SET_CURRENT_CARECOMPANY'
export const SET_CARECOMPANIES = 'SET_CARECOMPANIES'
export const SET_SELECTED_DATA = 'SET_SELECTED_DATA'

export const SET_SELECTED_DUTCH_DATA = 'SET_SELECTED_DUTCH_DATA'

export const ADD_TO_SHOPPING_BAG = 'ADD_TO_SHOPPING_BAG'
export const REMOVE_FROM_SHOPPING_BAG = 'REMOVE_FROM_SHOPPING_BAG'
export const INCREMENT_ITEM_AMOUNT = 'INCREMENT_ITEM_AMOUNT'
export const DECREMENT_ITEM_AMOUNT = 'DECREMENT_ITEM_AMOUNT'
export const SET_SUBSTITUTE_ITEMS = 'SET_SUBSTITUTE_ITEMS'

export const TOGGLE_AUTOCOMPLETE = 'TOGGLE_AUTOCOMPLETE'
export const TOGGLE_MENU = 'TOGGLE_MENU'
