export const SET_CURRENT_CARECOMPANY = 'SET_CURRENT_CARECOMPANY'
export const SET_CARECOMPANIES = 'SET_CARECOMPANIES'
export const SET_SELECTED_DATA = 'SET_SELECTED_DATA'

export const ADD_TO_SHOPPING_BAG = 'ADD_TO_SHOPPING_BAG'
export const REMOVE_FROM_SHOPPING_BAG = 'REMOVE_FROM_SHOPPING_BAG'
export const INCREMENT_ITEM_AMOUNT = 'INCREMENT_ITEM_AMOUNT'
export const DECREMENT_ITEM_AMOUNT = 'DECREMENT_ITEM_AMOUNT'
