const SET_CURRENT_CARECOMPANY = 'SET_CURRENT_CARECOMPANY'

const ADD_TO_SHOPPING_BAG = 'ADD_TO_SHOPPING_BAG'
const REMOVE_FROM_SHOPPING_BAG = 'REMOVE_FROM_SHOPPING_BAG'
const CHANGE_AMOUNT_OF_PRODUCT = 'CHANGE_AMOUNT_OF_PRODUCT'
